# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aliny Tristao
title: System Administrator
email: alinytristao@gmail.com
website: github.com/alinytristao

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: AlinyTristao
github_username:  alinytristao
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: alinytristao
linkedin_username: alinytristao
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: TristaoAG
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: In.myOpinion
  icon: fas fa-globe
  url: https://medium.com/@alinytristao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Aliny system administrator and Azure Cloud Arquitect.

  I am most skilled in: <mark>Windows Server</mark> and <mark>Azure</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/alinytristao/Elas-IT-Europe
        # link_text: Project Website
        additional_links:
          - title:  alinytristao/Elas-IT-Europe
            icon: fab fa-github
            url: github.com/alinytristao/Elas-IT-Europe
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest grups ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning and sharing <mark>IT information</mark> and it has since grown into a great community. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rumos Consulting
        link: rumos.pt/
        # link_text: boringcompany.com
        sub_title: System Administrator
        caption: March 2020 - Present
        quote: >
          Supporting business areas in a safe and effective way 
        description: | # this will include new lines to allow paragraphs
            Windows system administration, configurations in Azure, and Microsoft 365 services.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft Certified
        caption: 2023 -2024
        sub_title: Azure Solutions Architect Expert
        quote: >
          Azure Solutions Architect.
        description: | # this will include new lines to allow paragraphs
          Earning the Azure Solutions Architect Expert certification demonstrates subject matter expertise in designing cloud and hybrid solutions that run on Microsoft Azure, including compute, network, storage, monitoring, and security. Candidates have advanced experience and knowledge across IT operations, including networking, virtualization, identity, security, business continuity, disaster recovery, data platforms, and governance.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Azure and Clouds some of my other interests and hobbies are:
      - Devops
      - Security
      - Health
    #- [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #  Look at this cool image  
    #  ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
